### ISSUE TITLE
Check Mapping of 'mediaType' for EEXCESS providers

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#11]
When playing with Jarvis i found that a number of partners have a lot of unassigned results. For example, Mendeley, ZBW, Wissenmedia.

Could you please check the mapping? Also in unassigned might not be a very good category for the user. I would suggest providing a default `mediaType` mapping for a provider. This seems to be a more appropriate approach. For example, Wissemedia would always be a Text Result if not specified otherwise.

**Comment by jr-dig-orgel** [comment]
is changed and pushed, will be available after the next update
