### ISSUE TITLE
[KIM Portal Partern Recommender] Query Language seems to be wrongly used

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#14]
The KIM Portal uses a mixture of `+` and `OR` for expressing the query semantics. However, the `+` (meaning the succeeding word must be in the results|) seems to be used wrongly (namely as if it would mean `AND`).

For example:

the following entities

![screenshot 2015-08-24 13 36 32](https://cloud.githubusercontent.com/assets/1941683/9439194/2675d804-4a65-11e5-8ed0-d48c7fb85120.png)

yield to the following query

`(Ada+(programming+language) OR Lord+Byron OR Society OR England)`

and the following results 

![screenshot 2015-08-24 13 35 30](https://cloud.githubusercontent.com/assets/1941683/9439190/131530ac-4a65-11e5-91ac-a8caee5a34ee.png)

As it can be seen results contain Persons named Ada, but those results do not contain programming and language. From my point of view the correct query must be

`(+Ada+(programming+language) OR +Lord+Byron OR Society OR England)`

**Comment by hziak** [comment]
@jr-dig-orgel assigned it to you since i think thats your implemenation

**Comment by hziak** [comment]
just to clarify that:

shouldn't the query be 
"(Ada AND (programming AND language)) OR (Lord AND Byron) OR Society OR England"

**Comment by mgrani** [comment]
i think solr can be configured in different ways. i don't know what the correct format is.

**Comment by mgrani** [comment]
Just checked it with the link provided by KMBL: AND seems to be teh correct syntax for the endpoint: 
- [Auhafen AND Fotografien](https://kgapi.bl.ch/solr/kim-portal.objects/select/xml?q=_fulltext_:Auhafen%20AND%20Fotografie&rows=10) yields 58 results
- [Auhafen Fotografien](https://kgapi.bl.ch/solr/kim-portal.objects/select/xml?q=_fulltext_:Auhafen%20AND%20Fotografie&rows=10) yields 19079 results

**Comment by mgrani** [comment]
Seems like to be resolved for KIM. Or? If so please close the issue. Thanks.

**Comment by hziak** [comment]
Yes, should be resolved now
