### ISSUE TITLE
Partner Recommender Europeana: Wrong AND Syntax

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#17]
The queries generated by the Europeana partner recommender are not fully correct, since the AND operator requires brackets:

Terms: "Charles Babbage" "Analytical Engine"
Query Generated: [`Charles AND Babbage OR Analytical AND Engine`](http://www.europeana.eu/portal/search.html?query=Charles+AND+Babbage+OR+Analytical+AND+Engine&rows=24)
Correct Query: [`(Charles AND Babbage) OR (Analytical AND Engine)`](http://www.europeana.eu/portal/search.html?query=Charles+AND+Babbage+OR+Analytical+AND+Engine&rows=24)

**Comment by hziak** [comment]
Fixed and deployed on the know-demo server
Will be pushed to jr-dev shortly
