### ISSUE TITLE
FavIcons: Make Background Transparent

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#20]
The Favicon's should have a transparent background.

http://eexcess-dev.joanneum.at/eexcess-federated-recommender-web-service-1.0-SNAPSHOT/recommender/getPreviewImage?type=text

![Image showing the extension and the problem with non-transparent backgrounds](https://cloud.githubusercontent.com/assets/1941683/10046996/2e63b39c-620c-11e5-9eaa-bb00e2e48b90.png)

**Comment by hziak** [comment]
are there new images by now with transparent background?

**Comment by schloett** [comment]
updates are discussed in [issue 24](https://github.com/EEXCESS/chrome-extension/issues/24) of the chrome-extension repo

**Comment by chseifert** [comment]
Icons can be downloaded at https://www.dropbox.com/sh/xi7wcb43llz5bsw/AAACUYgCAdt3dOprPAU9iFU0a?dl=0
Herrman, could you notify me, when you have them :)

**Comment by hziak** [comment]
Done, is just in the process of being deployed

**Comment by hziak** [comment]
deployment done
can be reached at joanneum stable and dev via:

https://{server}/eexcess-federated-recommender-web-service-1.0-SNAPSHOT/recommender/getPreviewImage?type={type}
