### ISSUE TITLE
strange query behaviour for Europeana

### ISSUE THREAD

**Issue by schloett** [EEXCESS/recommender#23]
With Europeana selected as sole provider, I get 0 results when searching for a main topic only. For example, this query:
contextKeywords: [{text: "hilde", isMainTopic: true}]
yields 0 results
while that query:
contextKeywords: [{text: "hilde", isMainTopic: false}]
yields 17 results.
(requested 30 in both cases).
I did not check it for other providers, but when no particular provider is selected in the query profile, I get results.

**Comment by hziak** [comment]
Was a bug in the main topic generation.
Implemented but not deployed yet.

**Comment by hziak** [comment]
fix is deployed now on stable and development

**Comment by schloett** [comment]
Behavior did not change on stable server for me:
contextKeywords: [{text: "Loom", isMainTopic: true}] -> 0 results
contextKeywords: [{text: "Loom", isMainTopic: false}] -> 46 results
(requested only resources from Europeana)

**Comment by hziak** [comment]
somehow it didn't make it onto the stable or dev although it should have... will be fixed soon

**Comment by hziak** [comment]
now really deployed and fixed
