### ISSUE TITLE
Invalid URLs for RijksMuseum

### ISSUE THREAD

**Issue by kunzstef** [EEXCESS/recommender#24]
When openening the url of content from RijksMuseum there is always displayed "This art object is not yet available digitally" on their page. Maybe I have no access to the content or the URL is invalid.

**Comment by mgrani** [comment]
No, unfortunately a lot of objects from RijksMuseum are not available. This issue is from the rijksmuseum, not the recommender.

**Comment by chseifert** [comment]
Can't be solved by us.
