### ISSUE TITLE
[Data Mapping] Europeana Title

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#25]
It seems that for some items we get the title twice. The following example is obtained from https://en.wikipedia.org/wiki/Parachute paragraph Early Renessaince.

_Entry at Europeana_

<img width="843" alt="screen shot 2015-11-08 at 20 22 38" src="https://cloud.githubusercontent.com/assets/1941683/11022102/b14bd5f0-8656-11e5-9588-28d167954b34.png">

_Result Entry in Extension_
<img width="1190" alt="screen shot 2015-11-08 at 20 22 24" src="https://cloud.githubusercontent.com/assets/1941683/11022104/b4f30e08-8656-11e5-845e-e48c92ef29b1.png">

**Comment by mgrani** [comment]
it seems that some items with two languages have their titles and alternative titles appended. see for example http://europeana.eu/portal/record/08622/IWM_1004.html. 

I would only use the alternative titles when the main title is empty.

**Comment by jr-dig-orgel** [comment]
fixed with the last commit
