### ISSUE TITLE
[Data Provider] Kierling search does not return results by more than two query terms

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#30]
Main Topic support for Kierling seems to be incorrect. Searching for `Austria` as main topic  returns two results:
- http://culture.joanneum.at/catalog/online-katalog/?detail=29807e36-3686-465d-8605-2ce52669ef9d
- http://culture.joanneum.at/catalog/online-katalog/?detail=536cf640-453e-42de-9ea0-834199633c8b

Adding any other keyword to search in addition to austria, even those occuring in the text, does not yield any result.

Same with non Main-Topic Queries:
- `Berufe` yields 2 results
- `Rahmen` yields 64 resuls
- `Berufe` `Rahmen` (as topics) yields no result.

**Comment by jr-dig-orgel** [comment]
Kierling is generated with the https://github.com/EEXCESS/PartnerWizard

Actualy the PartnerWizard doesn't support the Main-Topic.

When we have integrated the KC-Part in the PartnerWizard we have support for this.
I will create a issue in the PartnerWizard.

When we have the integrated PartnerWizard we will generate new version from all already generated PartnerRecommenders.
