### ISSUE TITLE
Query Quality/Provider: Swiss Bib Provider returns multiple equal items

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#35]
Tested with Chrome Plugin Version Dev 1.7.4
1. Go to Ada Lovelace Web Page
2. Go to Paragraph Biography -> Childhood -> First Paragraph
3. Reduce Queries to `Augusta Leigh` as Main Topic and `Lord Byron` as Entity
4. open the results and select last tab (Tab for analysing the queries). Klick on Swissbib [64].
   --> 4 times entry Lord Byron Ton (identical resource) and also others.

**Comment by jr-dig-orgel** [comment]
I have fixed the problem and deployed the new version to our DEV-Server
