### ISSUE TITLE
Upper-/Lowercase mediaType

### ISSUE THREAD

**Issue by schloett** [EEXCESS/recommender#38]
for some providers the mediaType is uppercase (e.g. KimPortal - IMAGE), for some lowercase. Would be nice if this would be consistent across all providers and media types (again KimPortal - text ist lowercase).

**Comment by jr-dig-orgel** [comment]
I will change all mediaTypes to lowercase

**Comment by jr-dig-orgel** [comment]
fixed with the last commit
