### ISSUE TITLE
mediaType is always undefined

### ISSUE THREAD

**Issue by mathiasmoeller** [EEXCESS/recommender#4]
The recommender always returns `undefined` as `mediaType`.

See: https://www.dropbox.com/s/yw9hk3rbu0hwf5s/c4_recommender_results.json?dl=0

I have tested a few queries but they all have the same result.

**Comment by jr-dig-orgel** [comment]
is now fixed for the ParnterRecommenders:
europeana
DDB
KIMPortal
wissenmdia

**Comment by mathiasmoeller** [comment]
thanks it works fine now!
