### ISSUE TITLE
Language filtering does not work

### ISSUE THREAD

**Issue by mathiasmoeller** [EEXCESS/recommender#5]
Filtering the results via the languages attribute does not seem to work.

```
"languages":[
      {
         "iso2":"fr",
         }
]
```

for example returns all kind of languages

**Comment by hziak** [comment]
This feature rely on the source selection step and is not activated on the server yet.
Next deployment should happen next week.

**Comment by mathiasmoeller** [comment]
okay thanks for the info!

**Comment by mathiasmoeller** [comment]
@hziak could you give me an update about the source selection? i have a presentation on monday and i need to know if i have to disable the feature or not.
Thanks alot!

**Comment by hziak** [comment]
@mathiasmoeller 
If Thomas Orgel has time today to deploy the package on the server we can do it today.

**Comment by hziak** [comment]
@mathiasmoeller since i could not reach thomas yet as alternative you could try to use the knowcenter eexcess-demo server

**Comment by hziak** [comment]
new version supporting language select is deployed on the development server

**Comment by mathiasmoeller** [comment]
thanks alot!
