### ISSUE TITLE
Up-to-Date Exchange Format

### ISSUE THREAD

**Issue by treml05** [EEXCESS/recommender#6]
The current documentation for the json-exchange-format isn't online anymore.
I found some older ones but I cannot detect the new one. (including timeRange etc.) 

former directory:
https://github.com/EEXCESS/documentation/blob/ResultFormatChange/json-exchange-format.md

**Comment by hziak** [comment]
The new format has been relocated to the wiki and can be found here:
https://github.com/EEXCESS/documentation/wiki/json-exchange-format

**Comment by hziak** [comment]
Last post was the old format.
The new format has been relocated to the wiki and can be found here:
https://github.com/EEXCESS/eexcess/wiki/Request-and-Response-format-for-call-to-federated-recommender
