### ISSUE TITLE
Wrong preview images served

### ISSUE THREAD

**Issue by kunzstef** [EEXCESS/recommender#7]
For the provider "Deutsche Digitale Bibliothek" there is always a non existing preview image served.

**Comment by hziak** [comment]
Please give us some further details, like the query, since we can't reproduce the mentioned issue.

**Comment by kunzstef** [comment]
The uris of the delivered preview images could not be resolved for this provider, but this issue seams to be solved already. Problem doesn't occur anymore on dev server.
