### ISSUE TITLE
Make partner icons available via getRegisteredPartners and dedicated call

### ISSUE THREAD

**Issue by schloett** [EEXCESS/recommender#8]
As discussed, clients need to know the URL of partner icons. This URL will be present in the getRegisteredPartners call. Since some clients have limited storage capacities, we also need a service, that allows to retrieve the icons directly. (Otherwise some clients would need to preflight queries with a getRegisteredPartners call). An endpoint could for example be accessible in the following way:
 &lt;federatedRecommender&gt;/favicon/&lt;partnerID&gt;
 or 
 &lt;federatedRecommender&gt;/favicon?partner=&lt;partnerID&gt;
 This service then might redirect to the particular icon url.

[copied from jira, in particular, the GDOCS plugin requires the dedicated call]

**Comment by hziak** [comment]
new service can be tested on the kc demo server:
getPartnerFavIcon?partnerId={systemId}

example call: http://{server}/eexcess-federated-recommender-web-service-1.0-SNAPSHOT/recommender/getPartnerFavIcon?partnerId=Europeana

**Comment by chseifert** [comment]
Do you have estimates when the service will be available on the eexcess-dev server (JR)?

**Comment by schloett** [comment]
The icon for ZBW is missing, for the others it works fine, thanks. Looking forward to see it on the dev-server ;)

**Comment by hziak** [comment]
@helgeschneider the service could be deployed anytime but it depends on @jr-dig-orgel 

@schloett yes, thats because the icon url extracted from the official website seems to be broken http://www.zbw.de/favicon.ico, if anybody can give me an working url to the favicon i can change that

**Comment by schloett** [comment]
this one should work: http://www.zbw.eu/favicon.ico (zbw.de is the website of the "Ruhr Kolleg" - whatever this is...:))

**Comment by hziak** [comment]
hm ... thanks for the link ... anybody perhaps in close contact to tell them that their favicon is linking to zbw.de?
"link rel="shortcut icon" href="http://www.zbw.de/favicon.ico" " extracted from the zbw.eu source

I’m not sure if that's their intention actually.

**Comment by chseifert** [comment]
I'll do that

**Comment by chseifert** [comment]
service deployed 
http://eexcess-dev.joanneum.at/eexcess-federated-recommender-web-service-1.0-SNAPSHOT/recommender/getPartnerFavIcon?partnerId=Europeana
